name: Deploy to AWS ECR
on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ECR_REPOSITORY: desserts
  CONTAINER_NAME: desserts

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        run: |
          echo "[default]" > ~/.aws/config
          echo "region = ${{ env.AWS_REGION }}" >> ~/.aws/config

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{secrets.ACCOUNT_ID}}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY }} .
          docker tag ${{ env.ECR_REPOSITORY }}:latest ${{secrets.ACCOUNT_ID}}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Push Docker image to AWS ECR
        run: |
          docker push ${{secrets.ACCOUNT_ID}}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

    #   - name: Update ECS service with new task definition
    #     run: |
    #       aws ecs update-service --cluster your-ecs-cluster-name --service your-ecs-service-name --force-new-deployment
